name: Deploy to DockerHub

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou a versão que você utiliza

      # Passo 3: Instalar dependências e build
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Passo 4: Login no DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Passo 5: Construir e push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lanchonetews:latest
